---
# tasks/main.yml (prometheus)

- name: Install tasks
  import_tasks: install.yml
  when:
    - prometheus_install_flag | bool
  tags: ["install"]
- name: Configure tasks
  import_tasks: configure.yml
